# Generated by Django 5.2.4 on 2025-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('postre', 'Postre'), ('galleta', 'Galleta'), ('pudin', 'Pudín'), ('otro', 'Otro')], default='postre', max_length=20),
        ),
    ]
