# Generated by Django 6.0.2 on 2026-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tienda_producto "
                        "ADD COLUMN IF NOT EXISTS is_special boolean NOT NULL DEFAULT FALSE;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE tienda_producto "
                        "DROP COLUMN IF EXISTS is_special;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='is_special',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
