# Generated by Django 6.0.2 on 2026-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
