# Generated by Django 6.0.2 on 2026-02-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_is_special'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tienda_producto "
                        "ADD COLUMN IF NOT EXISTS ingredients text NOT NULL DEFAULT '';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE tienda_producto "
                        "DROP COLUMN IF EXISTS ingredients;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='ingredients',
                    field=models.TextField(blank=True, verbose_name='Ingredientes'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('postre', 'Postre'), ('torta_fria', 'Torta Fría'), ('pudin', 'Pudín'), ('otro', 'Otro')], default='postre', max_length=20),
        ),
    ]
