import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_password_reset_code_if_missing(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    user_model = apps.get_model(user_app_label, user_model_name)
    user_table = user_model._meta.db_table
    password_reset_table = 'tienda_passwordresetcode'
    table_names = schema_editor.connection.introspection.table_names()
    if password_reset_table in table_names:
        return

    schema_editor.execute(
        f"""
        CREATE TABLE {password_reset_table} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email varchar(254) NOT NULL,
            code_hash varchar(128) NOT NULL,
            attempts smallint NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL,
            last_sent_at timestamptz NOT NULL,
            expires_at timestamptz NOT NULL,
            verified_at timestamptz NULL,
            used_at timestamptz NULL,
            user_id integer NOT NULL REFERENCES {user_table} (id) DEFERRABLE INITIALLY DEFERRED
        );
        """
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS tienda_pass_email_5d4a41_idx "
        "ON tienda_passwordresetcode (email, created_at);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS tienda_pass_user_id_c79d85_idx "
        "ON tienda_passwordresetcode (user_id, created_at);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS tienda_pass_expires_4d9672_idx "
        "ON tienda_passwordresetcode (expires_at);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_ingredients_alter_producto_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_password_reset_code_if_missing,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PasswordResetCode',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('email', models.EmailField(max_length=254)),
                        ('code_hash', models.CharField(max_length=128)),
                        ('attempts', models.PositiveSmallIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('expires_at', models.DateTimeField()),
                        ('verified_at', models.DateTimeField(blank=True, null=True)),
                        ('used_at', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['email', 'created_at'], name='tienda_pass_email_5d4a41_idx'), models.Index(fields=['user', 'created_at'], name='tienda_pass_user_id_c79d85_idx'), models.Index(fields=['expires_at'], name='tienda_pass_expires_4d9672_idx')],
                    },
                ),
            ],
        ),
    ]
