# Generated by Django 6.0.2 on 2026-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpedido',
            name='event_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudpedido',
            name='occasion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudpedido',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudpedido',
            name='status',
            field=models.CharField(choices=[('recibido', 'Pedido recibido'), ('preparacion', 'En preparación'), ('envio', 'En camino'), ('entregado', 'Entregado')], default='recibido', max_length=20),
        ),
    ]
