# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_solicitudpedido_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='address_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='solicitudpedido',
            name='address_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
