# Generated by Django 6.0.2 on 2026-03-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_solicitudpedido_address_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpedido',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
