# Generated by Django 6.0.2 on 2026-03-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_solicitudpedido_address_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpedido',
            name='address_lat',
        ),
        migrations.RemoveField(
            model_name='solicitudpedido',
            name='address_lng',
        ),
    ]
